### ISSUE TITLE
Subarrays support

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_pipeline#11]
@arunsurya77 to provide test FITS files, path on Galactica is fine.

@zonca to implement support in `iris_pipeline`

**Comment by arunsurya77** [comment]
the subarray readouts are in /data/group/data/iris/readouts

**Comment by zonca** [comment]
thanks, I created a test file by injecting one of the readouts in one of Nil's simulated frames: https://gist.github.com/zonca/aed9e365393d500e4332a4ddf201c688

**Comment by zonca** [comment]
dark subtraction works fine on subarrays, also `stpipe` automatically recognizes `override_dark`: https://gist.github.com/zonca/1dca26dea35c9079a2df8ebb5dfb32f9

**Comment by zonca** [comment]
implemented in #14
