### ISSUE TITLE
Default subarray keywords for full frames

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_pipeline#13]
@nils-erik @arunsurya77 

I see that the default subarray parameters coming from the simulator are:

```
SUBSTRT1=1, SUBSTRT2=1, SUBSIZE1=4096, SUBSIZE2=4096
```

for a full array, shouldn't we have the `SUBSTRT` keywords be 0? or do you have any convention I don't know about arrays starting at 0 or 1?

**Comment by arunsurya77** [comment]
I am not sure why these keywords are not  XSTART,YSTART,XSIZE,YSIZE. maybe
it's an old file. Also yes you are correct, the start should be 0.
XSTART=0,YSTART=0

**Comment by zonca** [comment]
@nils-erik could it be due to IDL being 1-based instead of 0-based?
I'll change all the files to have xstart and ystart at 0, but we should make sure to propagate it back to the simulator.

**Comment by zonca** [comment]
actually I take it back, checking JWST code [1], the default  `xstart` and `ystart` is supposed to be 1,
I think that is due to the fact that the FITS file format defaults to 1-based indexing.
So let's use the same default in IRIS.

[1] https://github.com/spacetelescope/jwst/blob/187a6cf97ffef368699b6fff5d4925ecacd4a0f1/jwst/lib/reffile_utils.py#L100
