### ISSUE TITLE
Improve testing of ROP

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_pipeline#28]
Currently ROP is just executed with a uniform input ramp without checking its outputs.

It would be nice instead to first generate on the fly a more complicated input ramp, and then check that the different sampling algorithms work as expected (we can use small 10x10 arrays and save the outputs).

**Comment by arunsurya77** [comment]
Yes , I have written aa generate ramp and testing on the fly with better
tests. Since now the Travis integration works I can push some of these new
tests.

**Comment by zonca** [comment]
@arunsurya77 can you make a pull request with what tests have now? even if incomplete or not working, I can at least use it as a starting point.

**Comment by arunsurya77** [comment]
Hi ,
I have added the on the fly test function in the test_rop.py file in the
tests. I added it as a new test and added an assert check on the mean value
of the frame.
https://github.com/arunsurya77/iris_pipeline/blob/master/iris_pipeline/tests/test_rop.py

I think maybe we should just use this test for now without the file
dependent test. I haven't removed the old test.

Cheers
Arun

**Comment by zonca** [comment]
thanks @arunsurya77, is there a way to compute analytically the mean of the frame?
if so, it would be nice if you can explain here so I can copy into test

**Comment by arunsurya77** [comment]
Sorry @zonca . just saw this now. Somehow didn't see in the mail. I'm thinking how this test could be like analytic since the analytic formulae are what is used in the code. So checking with the same will not make sense. let me check in other sampling implementations how they setup their tests.

**Comment by zonca** [comment]
ok nevermind, I think it is fine
